
package CSTutor.View.Tutorial;

import CSTutor.Model.Tutorial.*;

import javax.swing.*;
import java.util.*;
import static javax.swing.JOptionPane.*;

/**
 * View for tutorial editing by an instructor.
 * @author Kim Arre
 * @version 27Apr2015
 */
public class EditTutorial extends javax.swing.JPanel {

    /**
     * Constructs a new instance of EditTutorial
     */
    public EditTutorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        descLabel = new javax.swing.JLabel();
        syntaxLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descText = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        syntaxText = new javax.swing.JTextPane();
        codeExampleLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        outputText = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        sampleCodeText = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tryItText = new javax.swing.JTextPane();
        tryItLabel = new javax.swing.JLabel();
        enterExerciseLabel = new javax.swing.JLabel();
        previewButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        toolsButton = new javax.swing.JButton();

        titleLabel.setText("Title:");

        descLabel.setText("Description");

        syntaxLabel.setText("Syntax");

        jScrollPane1.setViewportView(descText);

        jScrollPane2.setViewportView(syntaxText);

        codeExampleLabel.setText("Code Example");

        outputLabel.setText("Sample Output");

        jScrollPane4.setViewportView(outputText);

        jScrollPane5.setViewportView(sampleCodeText);

        javax.swing.GroupLayout descPanelLayout = new javax.swing.GroupLayout(descPanel);
        descPanel.setLayout(descPanelLayout);
        descPanelLayout.setHorizontalGroup(
            descPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descPanelLayout.createSequentialGroup()
                .addGroup(descPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(descPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(descPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(titleLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(titleField))
                        .addComponent(codeExampleLabel)
                        .addComponent(descLabel)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(descPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(outputLabel)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(descPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(syntaxLabel)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        descPanelLayout.setVerticalGroup(
            descPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(descPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(descLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(syntaxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(codeExampleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jScrollPane3.setViewportView(tryItText);

        tryItLabel.setText("Try It Yourself Student Exercise:");

        enterExerciseLabel.setText("Input your student exercise.");

        previewButton.setText("Preview");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        toolsButton.setText("Tools...");
        toolsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(toolsButton)
                        .addGap(35, 35, 35)
                        .addComponent(previewButton)
                        .addGap(34, 34, 34)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(enterExerciseLabel))
                        .addComponent(tryItLabel)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tryItLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterExerciseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(descPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /** 
     * Opens a new instance of the toolbar (EditingTools).
     */
    private void toolsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsButtonActionPerformed
        //toolbar = new EditingTools();
        //toolbar.setVisible(true);
        toolbar = new EditingTools();
        toolbar.setVisible(true);
    }//GEN-LAST:event_toolsButtonActionPerformed

    /** 
    * Opens a new instance of a Tutorial from the student's perspective.
    */
    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
      
        // fill in tutorial components
        JFrame tempFrame = new JFrame();
        tempFrame.setSize(1075, 700);
        
        TutorialData pageData = retrieveData();
        
        previewTutorial = new Tutorial(pageData);
        
        previewTutorial.disableButtons();
        
        tempFrame.add(previewTutorial);
        tempFrame.setVisible(true);
    }//GEN-LAST:event_previewButtonActionPerformed

    /**
     * Returns a TutorialData object to pass around for various uses.
     */
    private TutorialData retrieveData() {
        TutorialData pageData = new TutorialData();
        
        pageData.setTitle(titleField.getText());
        pageData.setDescription(descText.getText());
        pageData.setSyntax(syntaxText.getText());
        pageData.setExampleCode(sampleCodeText.getText());
        pageData.setExampleOutput(outputText.getText());
        pageData.tryItYourself = tryItText.getText();
        
        return pageData;
    }
    
    /**
     * Opens a new instance of the save confirmation dialog box.
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Make the tutorial object
        JOptionPane confirmation = new JOptionPane();
        int result = confirmation.showConfirmDialog(null, "Are you sure you want to save?", "Confirm Save", YES_NO_OPTION);
        
        if (result == YES_OPTION) {
            System.out.println("Confirmed!");
            editTut = new CSTutor.Model.Tutorial.TutorialEditor();
            TutorialData temp = retrieveData();
            editTut.save();
            
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /** Contains the editing tools needed for authors to personalize tutorial text */
    public EditingTools toolbar;
    
    /** Window for previewing the tutorial content input before saving */
    public Tutorial previewTutorial;
    
    /** Data structure for tutorial editing functionality. */
    public CSTutor.Model.Tutorial.TutorialEditor editTut;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codeExampleLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JPanel descPanel;
    private javax.swing.JTextPane descText;
    private javax.swing.JLabel enterExerciseLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JTextPane outputText;
    private javax.swing.JButton previewButton;
    private javax.swing.JTextPane sampleCodeText;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel syntaxLabel;
    private javax.swing.JTextPane syntaxText;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toolsButton;
    private javax.swing.JLabel tryItLabel;
    private javax.swing.JTextPane tryItText;
    // End of variables declaration//GEN-END:variables
}
