package CSTutor.View.Tutorial;

/**
 * EditingTools is the editing toolbar that shows during tutorial editing.
 * 
 * @author Kim Arre (karre@calpoly.edu)
 * @version 26Apr2015
 */
public class EditingTools extends javax.swing.JFrame {

    /**
     * Constructs a new instance of the EditingTools
     */
    public EditingTools() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        fontStyle = new javax.swing.JComboBox();
        fontSize = new javax.swing.JComboBox();
        isBold = new javax.swing.JToggleButton();
        isItalic = new javax.swing.JToggleButton();
        isUnderlined = new javax.swing.JToggleButton();
        fontColor = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        fontStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Times New Roman", "Courier New", "Ubuntu", "Helvetica Neue" }));
        jToolBar1.add(fontStyle);

        fontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "10", "12", "14", "16", "18", "20", "22", "24" }));
        jToolBar1.add(fontSize);

        isBold.setText("bold");
        isBold.setFocusable(false);
        isBold.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        isBold.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(isBold);

        isItalic.setText("italic");
        isItalic.setFocusable(false);
        isItalic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        isItalic.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(isItalic);

        isUnderlined.setText("underline");
        isUnderlined.setFocusable(false);
        isUnderlined.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        isUnderlined.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(isUnderlined);

        fontColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Blue", "Red", "Purple", "Green", "Orange"}));
        jToolBar1.add(fontColor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Opens and shows the toolbar
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditingTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditingTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditingTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditingTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditingTools().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fontColor;
    private javax.swing.JComboBox fontSize;
    private javax.swing.JComboBox fontStyle;
    private javax.swing.JToggleButton isBold;
    private javax.swing.JToggleButton isItalic;
    private javax.swing.JToggleButton isUnderlined;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
