/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CSTutor.View.Tutorial;

import CSTutor.Model.Tutorial.*;
import java.util.*;
import javax.swing.JFrame;

/**
 * Contains the elements of the tutorial view
 * 
 * @author Kim Arre (karre@calpoly.edu)
 * @version 26Apr2015
 */
public class Tutorial extends javax.swing.JPanel {
    /** Overall structure containing tutorial content */
    private LinkedList<TutorialData> tutorialTrack = new LinkedList();
    private int currentIndex = 0;
    
    /** Provides a quick way to jump between tutorial lessons */
    public RoadmapModule sideModule;
    
    /**
     * Creates new Tutorial with two sample initial tutorials
     */
    public Tutorial() {
        initComponents();
        enableLineWrap();
        sideModule = new RoadmapModule();
        
        JFrame tempFrame = new JFrame();
        tempFrame.setSize(1075, 700);
        
        // First sample tutorial Content
        TutorialData first = new TutorialData();
        first.setTitle("For Loops");
        first.setDescription("For loops are a type of control structure that "
          + "allow code to be repeatedly executed. They take three arguments"
          + " in the order of:\n     1. starting condition;\n     2. condition "
          + "to exit the loop;\n     3. post loop increment");
        
        first.setSyntax("for (int i=start; i<upperLimit; i++) {\n   ...\n}");
        first.setExampleOutput("Hello world\nHello world\nHello world\nHello world\nHello world");
        first.setExampleCode("for (int i=0; i<5; i++) {\n    printf(\"Hello world\\n\");\n}");
        tutorialTrack.add(first);
        
        // Second sample tutorial content
        TutorialData second = new TutorialData();
        second.setTitle("While Loops");
        second.setDescription("While loops are only sometimes as cool as for loops.");
        tutorialTrack.add(second);
        
        setAllTheThings(tutorialTrack.peekFirst());
        
        tempFrame.add(this);
        tempFrame.setVisible(true);
    }
    
    /**
     * Creates a new one page tutorial with the given TutorialData
     * @param pageData Data to fill the tutorial content with.
     */
    public Tutorial(TutorialData pageData) {
        initComponents();
        enableLineWrap();
        setAllTheThings(pageData);
    }
    
    /**
     * Sets all components of the tutorial
     * @param pageData Contains the tutorial elements to set
     */
    public void setAllTheThings(TutorialData pageData) {
        titleLabel.setText("<html><b>" + pageData.title + "</b></html>");
        descText.setText(pageData.getDescription());
        syntaxText.setText(pageData.getSyntax());
        sampleCodeText.setText(pageData.getExampleCode());
        sampleOutputText.setText(pageData.getExampleOutput());
        tryItText.setText(pageData.tryItYourself);
    }
    
    /** Enables line wrap for all text elements since NetBeans is a control 
     * freak and won't let me edit the init function. 
     */
    private void enableLineWrap() {
        descText.setLineWrap(true);
        descText.setWrapStyleWord(true);
        
        syntaxText.setLineWrap(true);
        syntaxText.setWrapStyleWord(true);
        
        sampleCodeText.setLineWrap(true);
        sampleCodeText.setWrapStyleWord(true);
        
        sampleOutputText.setLineWrap(true);
        sampleOutputText.setWrapStyleWord(true);
        
        tryItText.setLineWrap(true);
        tryItText.setWrapStyleWord(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        toEndButton = new javax.swing.JButton();
        toBeginningButton = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        roadmapList = new javax.swing.JList();
        descriptionPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        descText = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        sampleCodeText = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        sampleOutputText = new javax.swing.JTextArea();
        sampleCodeLabel = new javax.swing.JLabel();
        sampleOutputLabel = new javax.swing.JLabel();
        syntaxLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        syntaxText = new javax.swing.JTextArea();
        descLabel = new javax.swing.JLabel();
        TryItYourself = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        codeInputText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        consoleText = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tryItText = new javax.swing.JTextArea();
        titleLabel = new javax.swing.JLabel();
        previousLessonButton = new javax.swing.JButton();
        nextLessonButton = new javax.swing.JButton();

        toEndButton.setText("Jump to End");
        toEndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toEndButtonActionPerformed(evt);
            }
        });

        toBeginningButton.setText("Jump to Beginning");
        toBeginningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBeginningButtonActionPerformed(evt);
            }
        });

        roadmapList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(roadmapList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9)
                    .addComponent(toEndButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toBeginningButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(toBeginningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toEndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        descText.setColumns(20);
        descText.setRows(5);
        jScrollPane5.setViewportView(descText);

        sampleCodeText.setColumns(20);
        sampleCodeText.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        sampleCodeText.setRows(5);
        jScrollPane6.setViewportView(sampleCodeText);

        sampleOutputText.setColumns(20);
        sampleOutputText.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        sampleOutputText.setRows(5);
        jScrollPane7.setViewportView(sampleOutputText);

        sampleCodeLabel.setText("<html><b>Code Example</html></b>");

        sampleOutputLabel.setText("<html><b>Output</html></b>");

        syntaxLabel.setText("<html><b>Syntax</html></b>");

        syntaxText.setColumns(20);
        syntaxText.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        syntaxText.setRows(5);
        jScrollPane8.setViewportView(syntaxText);

        descLabel.setText("<html><b>Description</b></html>");

        codeInputText.setColumns(20);
        codeInputText.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        codeInputText.setRows(5);
        codeInputText.setText("1 \n2 \n3 \n4 \n5 \n6 \n7 \n8 \n9 \n");
        jScrollPane3.setViewportView(codeInputText);

        consoleText.setColumns(20);
        consoleText.setRows(5);
        jScrollPane4.setViewportView(consoleText);

        jButton3.setText("Run");

        jLabel1.setText("<html><b>Try It Yourself!</html></b>");

        tryItText.setColumns(20);
        tryItText.setRows(5);
        jScrollPane2.setViewportView(tryItText);

        javax.swing.GroupLayout TryItYourselfLayout = new javax.swing.GroupLayout(TryItYourself);
        TryItYourself.setLayout(TryItYourselfLayout);
        TryItYourselfLayout.setHorizontalGroup(
            TryItYourselfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TryItYourselfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TryItYourselfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(TryItYourselfLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TryItYourselfLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        TryItYourselfLayout.setVerticalGroup(
            TryItYourselfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TryItYourselfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout descriptionPanelLayout = new javax.swing.GroupLayout(descriptionPanel);
        descriptionPanel.setLayout(descriptionPanelLayout);
        descriptionPanelLayout.setHorizontalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addGroup(descriptionPanelLayout.createSequentialGroup()
                        .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sampleOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sampleCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(syntaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TryItYourself, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        descriptionPanelLayout.setVerticalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(syntaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sampleCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sampleOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(TryItYourself, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        previousLessonButton.setText("Previous Lesson");
        previousLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousLessonButtonActionPerformed(evt);
            }
        });

        nextLessonButton.setText("Next Lesson");
        nextLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextLessonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(descriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(previousLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(descriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(previousLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /** 
     * Update the tutorial to the current roadmap selection. 
     */
    private void RoadmapContentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_RoadmapContentListValueChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_RoadmapContentListValueChanged
    
    /** 
     * Jump to the end of the tutorial track.
     */
    private void toEndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toEndButtonActionPerformed
        sideModule.toEnd();
    }//GEN-LAST:event_toEndButtonActionPerformed

    /**
     * Load content for the previous lesson.
     */
    private void previousLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousLessonButtonActionPerformed
        if (currentIndex > 0) {
            currentIndex--;
        }
        setAllTheThings(tutorialTrack.get(currentIndex));
        System.out.println("Tutorial " + (currentIndex+1) + "/" + tutorialTrack.size());
    }//GEN-LAST:event_previousLessonButtonActionPerformed

    /**
     * Load content for the next lesson
     */
    private void nextLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextLessonButtonActionPerformed
        if (currentIndex < tutorialTrack.size() - 1) {
            currentIndex++;
        }
        setAllTheThings(tutorialTrack.get(currentIndex));
        System.out.println("Tutorial " + (currentIndex+1) + "/" + tutorialTrack.size());
    }//GEN-LAST:event_nextLessonButtonActionPerformed

    /**
     * Jump to the beginning of the tutorial track
     */
    private void toBeginningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBeginningButtonActionPerformed
        sideModule.toBeginning();
    }//GEN-LAST:event_toBeginningButtonActionPerformed

    /**
     * Opens and shows the Tutorial
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditingTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditingTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditingTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditingTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorial().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TryItYourself;
    private javax.swing.JTextArea codeInputText;
    private javax.swing.JTextArea consoleText;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextArea descText;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton nextLessonButton;
    private javax.swing.JButton previousLessonButton;
    private javax.swing.JList roadmapList;
    private javax.swing.JLabel sampleCodeLabel;
    private javax.swing.JTextArea sampleCodeText;
    private javax.swing.JLabel sampleOutputLabel;
    private javax.swing.JTextArea sampleOutputText;
    private javax.swing.JLabel syntaxLabel;
    private javax.swing.JTextArea syntaxText;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toBeginningButton;
    private javax.swing.JButton toEndButton;
    private javax.swing.JTextArea tryItText;
    // End of variables declaration//GEN-END:variables
}
