/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CSTutor.View.Tutorial;

import CSTutor.Model.Tutorial.*;

/**
 *
 * @author Kim Arre (karre@calpoly.edu)
 * @version 20Apr2015
 */
public class Tutorial extends javax.swing.JPanel {

    /**
     * Creates new form Tutorial
     */
    public Tutorial() {
        initComponents();
        sideModule = new RoadmapModule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoadmapContentList = new javax.swing.JList();
        toEndButton = new javax.swing.JButton();
        toBeginningButton = new javax.swing.JButton();
        descriptionPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        codeExampleText = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        outputTextbox = new javax.swing.JTextArea();
        codeExampleLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        syntaxLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        syntaxTextbox = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        TryItYourself = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textEditorArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        consoleArea = new javax.swing.JTextArea();
        runButton = new javax.swing.JButton();
        tryItLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tryItTextbox = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        previousLessonButton = new javax.swing.JButton();
        nextLessonButton = new javax.swing.JButton();

        RoadmapContentList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Types/Variables", "Arrays", "If Statements", "For Loops", "While Loops", "Structs" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        RoadmapContentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                RoadmapContentListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(RoadmapContentList);

        toEndButton.setText("Jump to End");
        toEndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toEndButtonActionPerformed(evt);
            }
        });

        toBeginningButton.setText("Jump to Beginning");
        toBeginningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBeginningButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(toEndButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toBeginningButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(toBeginningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toEndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        descriptionText.setColumns(20);
        descriptionText.setRows(5);
        descriptionText.setText("For loops are a type of control structure that \nallow code to be repeatedly executed.\n\nThey take three arguments in the order of:\n   1. starting condition; \n   2. condition to exit the loop; \n   3. post loop increment");
        jScrollPane5.setViewportView(descriptionText);

        codeExampleText.setColumns(20);
        codeExampleText.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        codeExampleText.setRows(5);
        codeExampleText.setText("for (int i=0; i<5; i++) {\n    printf(\"Hello world\\n\");\n}");
        jScrollPane6.setViewportView(codeExampleText);

        outputTextbox.setColumns(20);
        outputTextbox.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        outputTextbox.setRows(5);
        outputTextbox.setText("Hello world\nHello world\nHello world\nHello world\nHello world");
        jScrollPane7.setViewportView(outputTextbox);

        codeExampleLabel.setText("<html><b>Code Example</html></b>");

        outputLabel.setText("<html><b>Output</html></b>");

        syntaxLabel.setText("<html><b>Syntax</html></b>");

        syntaxTextbox.setColumns(20);
        syntaxTextbox.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        syntaxTextbox.setRows(5);
        syntaxTextbox.setText("for (int i=start; i<upperLimit; i++) {\n   ...\n}");
        jScrollPane8.setViewportView(syntaxTextbox);

        descriptionLabel.setText("<html><b>Description THIS IS A TEST</b></html>");

        textEditorArea.setColumns(20);
        textEditorArea.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        textEditorArea.setRows(5);
        textEditorArea.setText("1 \n2 \n3 \n4 \n5 \n6 \n7 \n8 \n9 \n");
        jScrollPane3.setViewportView(textEditorArea);

        consoleArea.setColumns(20);
        consoleArea.setRows(5);
        jScrollPane4.setViewportView(consoleArea);

        runButton.setText("Run");

        tryItLabel.setText("<html><b>Try It Yourself!</html></b>");

        tryItTextbox.setColumns(20);
        //tryItTextbox.setRows(5);
        tryItTextbox.setText("poop");
        jScrollPane2.setViewportView(tryItTextbox);

        javax.swing.GroupLayout TryItYourselfLayout = new javax.swing.GroupLayout(TryItYourself);
        TryItYourself.setLayout(TryItYourselfLayout);
        TryItYourselfLayout.setHorizontalGroup(
            TryItYourselfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TryItYourselfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TryItYourselfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(TryItYourselfLayout.createSequentialGroup()
                        .addComponent(tryItLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TryItYourselfLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(runButton))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        TryItYourselfLayout.setVerticalGroup(
            TryItYourselfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TryItYourselfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tryItLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        titleLabel.setText("For Loops");

        javax.swing.GroupLayout descriptionPanelLayout = new javax.swing.GroupLayout(descriptionPanel);
        descriptionPanel.setLayout(descriptionPanelLayout);
        descriptionPanelLayout.setHorizontalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addGroup(descriptionPanelLayout.createSequentialGroup()
                        .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeExampleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(syntaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TryItYourself, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        descriptionPanelLayout.setVerticalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(syntaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codeExampleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(TryItYourself, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        previousLessonButton.setText("Previous Lesson");
        previousLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousLessonButtonActionPerformed(evt);
            }
        });

        nextLessonButton.setText("Next Lesson");
        nextLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextLessonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(descriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(previousLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(descriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(previousLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RoadmapContentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_RoadmapContentListValueChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_RoadmapContentListValueChanged

    private void toEndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toEndButtonActionPerformed
        sideModule.toEnd();
    }//GEN-LAST:event_toEndButtonActionPerformed

    private void previousLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousLessonButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousLessonButtonActionPerformed

    private void nextLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextLessonButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextLessonButtonActionPerformed

    private void toBeginningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBeginningButtonActionPerformed
        sideModule.toBeginning();
    }//GEN-LAST:event_toBeginningButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList RoadmapContentList;
    private javax.swing.JPanel TryItYourself;
    private javax.swing.JLabel codeExampleLabel;
    private javax.swing.JTextArea codeExampleText;
    private javax.swing.JTextArea consoleArea;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton nextLessonButton;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JTextArea outputTextbox;
    private javax.swing.JButton previousLessonButton;
    private javax.swing.JButton runButton;
    private javax.swing.JLabel syntaxLabel;
    private javax.swing.JTextArea syntaxTextbox;
    private javax.swing.JTextArea textEditorArea;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toBeginningButton;
    private javax.swing.JButton toEndButton;
    private javax.swing.JLabel tryItLabel;
    private javax.swing.JTextField tryItTextbox;
    // End of variables declaration//GEN-END:variables
    public RoadmapModule sideModule;
}
